# Generated by Django 3.1.5 on 2021-02-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_auto_20210223_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='/static/img/portfolio/default.png', null=True, upload_to='profile/'),
        ),
    ]
