# Generated by Django 3.1.5 on 2021-02-23 11:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Single_Question',
            new_name='Question',
        ),
    ]
