# Generated by Django 3.1.5 on 2021-02-15 12:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20210215_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='learn',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='learn',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='learn',
            name='purport',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
