# Generated by Django 3.1.5 on 2021-02-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(),
        ),
    ]
