# Generated by Django 3.1.5 on 2021-02-15 19:53

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0005_auto_20210215_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Single_Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', ckeditor.fields.RichTextField()),
                ('image', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Single_Arte', to='Home.article')),
                ('by_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
