# Generated by Django 3.1.5 on 2021-02-16 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_remove_comment_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.single_art'),
        ),
    ]
